import config from '../../config/index'

export default [
    `${config.cdnUrl}/logo-b.png`,
    `${config.cdnUrl}/logo-w.png`,
    `${config.cdnUrl}/post-1.png`,
    `${config.cdnUrl}/post-2.png`,
    `${config.cdnUrl}/post-3.png`,
    `${config.cdnUrl}/post-4.png`,
    `${config.cdnUrl}/post-5.png`,
    `${config.cdnUrl}/btn-1.png`,
    `${config.cdnUrl}/btn-2.png`,
    `${config.cdnUrl}/btn-3.png`,
    `${config.cdnUrl}/btn-4.png`,
    `${config.cdnUrl}/btn-5.png`,
    `${config.cdnUrl}/btn-1-a.png`,
    `${config.cdnUrl}/btn-2-a.png`,
    `${config.cdnUrl}/btn-3-a.png`,
    `${config.cdnUrl}/btn-4-a.png`,
    `${config.cdnUrl}/btn-5-a.png`,
    `${config.cdnUrl}/btn-s-a.png`,
    `${config.cdnUrl}/btn-l-a.png`,
    `${config.cdnUrl}/btn-s.png`,
    `${config.cdnUrl}/btn-l.png`,
    `${config.cdnUrl}/title.png`,
    `${config.cdnUrl}/start.png`,
    `${config.cdnUrl}/start-a.png`,
    `${config.cdnUrl}/qstitle-1.png`,
    `${config.cdnUrl}/qstitle-2.png`,
    `${config.cdnUrl}/award-1.png`,
    `${config.cdnUrl}/award-2.png`,
    `${config.cdnUrl}/award-3.png`,
    `${config.cdnUrl}/award-4.png`,
    `${config.cdnUrl}/award-5.png`,
    `${config.cdnUrl}/box.png`,
    `${config.cdnUrl}/title2.png`
]